### ISSUE TITLE
Memory access fault by GPU node-1. Reason: Page not present or supervisor privilege.

### ISSUE THREAD

**Issue by quizzicus** [SanDiegoDude/ComfyUI-HiDream-Sampler#23]
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-04-15 10:08:20.207
** Platform: Linux
** Python version: 3.11.11 (main, Feb 10 2025, 00:00:00) [GCC 15.0.1 20250204 (Red Hat 15.0.1-0)]
** Python executable: /usr/bin/python3.11
** ComfyUI Path: /media/sandbox/ComfyUI
** ComfyUI Base Folder Path: /media/sandbox/ComfyUI
** User directory: /media/sandbox/ComfyUI/user
** ComfyUI-Manager config path: /media/sandbox/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /media/sandbox/ComfyUI/user/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /media/sandbox/ComfyUI/custom_nodes/rgthree-comfy
   2.0 seconds: /media/sandbox/ComfyUI/custom_nodes/ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 24560 MB, total RAM 128719 MB
pytorch version: 2.7.0.dev20250312+rocm6.3
AMD arch: gfx1100
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7900 XTX : native
Using pytorch attention
ComfyUI version: 0.3.27
ComfyUI frontend version: 1.15.13
[Prompt Server] web root: /home/john/.local/lib/python3.11/site-packages/comfyui_frontend_package/static
/home/john/.local/lib/python3.11/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V3.31.9)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.27-37-g22ad513c | Released on '2025-04-11'

[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉

Flash Attention 2 is not available, will use PyTorch's native attention if possible.
PyTorch SDPA (Scaled Dot Product Attention) is available.
GPTQModel (transformers) support is available (recommended).
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-04-15 10:08:29.868972: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1744726109.885640   33314 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744726109.890741   33314 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744726109.903747   33314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744726109.903775   33314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744726109.903778   33314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744726109.903781   33314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-04-15 10:08:29.908179: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
PyTorch version 2.7.0.dev20250312+rocm6.3 available.
TensorFlow version 2.19.0 available.
JAX version 0.5.3 available.
/home/john/.local/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:410: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/home/john/.local/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:418: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd
/home/john/.local/lib/python3.11/site-packages/auto_gptq/nn_modules/triton_utils/kernels.py:461: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16)
CUDA extension not installed.
CUDA extension not installed.
auto_gptq support is available (legacy).
GPTQ support composite: (GPTQModel: True | auto_gptq: True) -> True
FETCH ComfyRegistry Data: 5/82
Flash Attention is not available for HiDream, will use PyTorch's native attention.
PyTorch SDPA (Scaled Dot Product Attention) is available for HiDream.
GPTQ dependencies available - all models should work
HiDream: Successfully registered with ComfyUI memory management
--------------------------------------------------
HiDream Sampler Node Initialized
Available Models: ['full-nf4', 'dev-nf4', 'fast-nf4', 'full', 'dev', 'fast']
--------------------------------------------------

Import times for custom nodes:
   0.0 seconds: /media/sandbox/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /media/sandbox/ComfyUI/custom_nodes/sd-dynamic-thresholding
   0.0 seconds: /media/sandbox/ComfyUI/custom_nodes/comfyui_memory_cleanup
   0.0 seconds: /media/sandbox/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /media/sandbox/ComfyUI/custom_nodes/ComfyUI-Manager
   3.5 seconds: /media/sandbox/ComfyUI/custom_nodes/ComfyUI-HiDream-Sampler

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH ComfyRegistry Data: 10/82
FETCH ComfyRegistry Data: 15/82
FETCH ComfyRegistry Data: 20/82
FETCH ComfyRegistry Data: 25/82
FETCH ComfyRegistry Data: 30/82
FETCH ComfyRegistry Data: 35/82
FETCH ComfyRegistry Data: 40/82
FETCH ComfyRegistry Data: 45/82
got prompt
Using resolution: 1024×1024 from aspect ratio: 1:1 (1024×1024)
HiDream: Initial VRAM usage: 0.00 MB
Loading model for fast-nf4...
--- Loading Model Type: fast-nf4 ---
Model Path: azaneko/HiDream-I1-Fast-nf4
NF4: True, Requires BNB: False, Requires GPTQ deps: True
Using alternate LLM: False
(Start VRAM: 0.00 MB)
Cache check for key: fast-nf4_standard
Cache contains: []

[1a] Preparing LLM (GPTQ): hugging-quants/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4
     Setting max memory limit: 9GiB of 24.0GiB
     Using device_map='auto'.
[1b] Loading Tokenizer: hugging-quants/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4...
     Tokenizer loaded.
     ✅ Fixed rope_scaling to: {'type': 'linear', 'factor': 1.0}
[GPTQ] Using transformers.GPTQConfig for quantization
/home/john/.local/lib/python3.11/site-packages/transformers/quantizers/auto.py:212: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.However, loading attributes (e.g. ['backend', 'use_cuda_fp16', 'use_exllama', 'max_input_length', 'exllama_config']) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
  warnings.warn(warning_msg)

INFO  ENV: Auto setting CUDA_DEVICE_ORDER=PCI_BUS_ID for correctness.                                                                                                                                           
Detected gptqmodel and auto-gptq, will use gptqmodel
INFO   Kernel: Auto-selection: adding candidate `ExllamaQuantLinear`                                                                                                                                            
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.
FETCH ComfyRegistry Data: 50/82
Detected gptqmodel and auto-gptq, will use gptqmodel
Loading checkpoint shards:   0%|                                                                                                                                                           | 0/2 [00:00<?, ?it/s]FETCH ComfyRegistry Data: 55/82
FETCH ComfyRegistry Data: 60/82
Loading checkpoint shards:  50%|█████████████████████████████████████████████████████████████████████████▌                                                                         | 1/2 [00:08<00:08,  8.67s/it]FETCH ComfyRegistry Data: 65/82
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.02s/it]
Some weights of the model checkpoint at hugging-quants/Meta-Llama-3.1-8B-Instruct-GPTQ-INT4 were not used when initializing LlamaForCausalLM: ['model.layers.0.mlp.down_proj.bias', 'model.layers.0.mlp.gate_proj.bias', 'model.layers.0.mlp.up_proj.bias', 'model.layers.0.self_attn.k_proj.bias', 'model.layers.0.self_attn.o_proj.bias', 'model.layers.0.self_attn.q_proj.bias', 'model.layers.0.self_attn.v_proj.bias', 'model.layers.1.mlp.down_proj.bias', 'model.layers.1.mlp.gate_proj.bias', 'model.layers.1.mlp.up_proj.bias', 'model.layers.1.self_attn.k_proj.bias', 'model.layers.1.self_attn.o_proj.bias', 'model.layers.1.self_attn.q_proj.bias', 'model.layers.1.self_attn.v_proj.bias', 'model.layers.10.mlp.down_proj.bias', 'model.layers.10.mlp.gate_proj.bias', 'model.layers.10.mlp.up_proj.bias', 'model.layers.10.self_attn.k_proj.bias', 'model.layers.10.self_attn.o_proj.bias', 'model.layers.10.self_attn.q_proj.bias', 'model.layers.10.self_attn.v_proj.bias', 'model.layers.11.mlp.down_proj.bias', 'model.layers.11.mlp.gate_proj.bias', 'model.layers.11.mlp.up_proj.bias', 'model.layers.11.self_attn.k_proj.bias', 'model.layers.11.self_attn.o_proj.bias', 'model.layers.11.self_attn.q_proj.bias', 'model.layers.11.self_attn.v_proj.bias', 'model.layers.12.mlp.down_proj.bias', 'model.layers.12.mlp.gate_proj.bias', 'model.layers.12.mlp.up_proj.bias', 'model.layers.12.self_attn.k_proj.bias', 'model.layers.12.self_attn.o_proj.bias', 'model.layers.12.self_attn.q_proj.bias', 'model.layers.12.self_attn.v_proj.bias', 'model.layers.13.mlp.down_proj.bias', 'model.layers.13.mlp.gate_proj.bias', 'model.layers.13.mlp.up_proj.bias', 'model.layers.13.self_attn.k_proj.bias', 'model.layers.13.self_attn.o_proj.bias', 'model.layers.13.self_attn.q_proj.bias', 'model.layers.13.self_attn.v_proj.bias', 'model.layers.14.mlp.down_proj.bias', 'model.layers.14.mlp.gate_proj.bias', 'model.layers.14.mlp.up_proj.bias', 'model.layers.14.self_attn.k_proj.bias', 'model.layers.14.self_attn.o_proj.bias', 'model.layers.14.self_attn.q_proj.bias', 'model.layers.14.self_attn.v_proj.bias', 'model.layers.15.mlp.down_proj.bias', 'model.layers.15.mlp.gate_proj.bias', 'model.layers.15.mlp.up_proj.bias', 'model.layers.15.self_attn.k_proj.bias', 'model.layers.15.self_attn.o_proj.bias', 'model.layers.15.self_attn.q_proj.bias', 'model.layers.15.self_attn.v_proj.bias', 'model.layers.16.mlp.down_proj.bias', 'model.layers.16.mlp.gate_proj.bias', 'model.layers.16.mlp.up_proj.bias', 'model.layers.16.self_attn.k_proj.bias', 'model.layers.16.self_attn.o_proj.bias', 'model.layers.16.self_attn.q_proj.bias', 'model.layers.16.self_attn.v_proj.bias', 'model.layers.17.mlp.down_proj.bias', 'model.layers.17.mlp.gate_proj.bias', 'model.layers.17.mlp.up_proj.bias', 'model.layers.17.self_attn.k_proj.bias', 'model.layers.17.self_attn.o_proj.bias', 'model.layers.17.self_attn.q_proj.bias', 'model.layers.17.self_attn.v_proj.bias', 'model.layers.18.mlp.down_proj.bias', 'model.layers.18.mlp.gate_proj.bias', 'model.layers.18.mlp.up_proj.bias', 'model.layers.18.self_attn.k_proj.bias', 'model.layers.18.self_attn.o_proj.bias', 'model.layers.18.self_attn.q_proj.bias', 'model.layers.18.self_attn.v_proj.bias', 'model.layers.19.mlp.down_proj.bias', 'model.layers.19.mlp.gate_proj.bias', 'model.layers.19.mlp.up_proj.bias', 'model.layers.19.self_attn.k_proj.bias', 'model.layers.19.self_attn.o_proj.bias', 'model.layers.19.self_attn.q_proj.bias', 'model.layers.19.self_attn.v_proj.bias', 'model.layers.2.mlp.down_proj.bias', 'model.layers.2.mlp.gate_proj.bias', 'model.layers.2.mlp.up_proj.bias', 'model.layers.2.self_attn.k_proj.bias', 'model.layers.2.self_attn.o_proj.bias', 'model.layers.2.self_attn.q_proj.bias', 'model.layers.2.self_attn.v_proj.bias', 'model.layers.20.mlp.down_proj.bias', 'model.layers.20.mlp.gate_proj.bias', 'model.layers.20.mlp.up_proj.bias', 'model.layers.20.self_attn.k_proj.bias', 'model.layers.20.self_attn.o_proj.bias', 'model.layers.20.self_attn.q_proj.bias', 'model.layers.20.self_attn.v_proj.bias', 'model.layers.21.mlp.down_proj.bias', 'model.layers.21.mlp.gate_proj.bias', 'model.layers.21.mlp.up_proj.bias', 'model.layers.21.self_attn.k_proj.bias', 'model.layers.21.self_attn.o_proj.bias', 'model.layers.21.self_attn.q_proj.bias', 'model.layers.21.self_attn.v_proj.bias', 'model.layers.22.mlp.down_proj.bias', 'model.layers.22.mlp.gate_proj.bias', 'model.layers.22.mlp.up_proj.bias', 'model.layers.22.self_attn.k_proj.bias', 'model.layers.22.self_attn.o_proj.bias', 'model.layers.22.self_attn.q_proj.bias', 'model.layers.22.self_attn.v_proj.bias', 'model.layers.23.mlp.down_proj.bias', 'model.layers.23.mlp.gate_proj.bias', 'model.layers.23.mlp.up_proj.bias', 'model.layers.23.self_attn.k_proj.bias', 'model.layers.23.self_attn.o_proj.bias', 'model.layers.23.self_attn.q_proj.bias', 'model.layers.23.self_attn.v_proj.bias', 'model.layers.24.mlp.down_proj.bias', 'model.layers.24.mlp.gate_proj.bias', 'model.layers.24.mlp.up_proj.bias', 'model.layers.24.self_attn.k_proj.bias', 'model.layers.24.self_attn.o_proj.bias', 'model.layers.24.self_attn.q_proj.bias', 'model.layers.24.self_attn.v_proj.bias', 'model.layers.25.mlp.down_proj.bias', 'model.layers.25.mlp.gate_proj.bias', 'model.layers.25.mlp.up_proj.bias', 'model.layers.25.self_attn.k_proj.bias', 'model.layers.25.self_attn.o_proj.bias', 'model.layers.25.self_attn.q_proj.bias', 'model.layers.25.self_attn.v_proj.bias', 'model.layers.26.mlp.down_proj.bias', 'model.layers.26.mlp.gate_proj.bias', 'model.layers.26.mlp.up_proj.bias', 'model.layers.26.self_attn.k_proj.bias', 'model.layers.26.self_attn.o_proj.bias', 'model.layers.26.self_attn.q_proj.bias', 'model.layers.26.self_attn.v_proj.bias', 'model.layers.27.mlp.down_proj.bias', 'model.layers.27.mlp.gate_proj.bias', 'model.layers.27.mlp.up_proj.bias', 'model.layers.27.self_attn.k_proj.bias', 'model.layers.27.self_attn.o_proj.bias', 'model.layers.27.self_attn.q_proj.bias', 'model.layers.27.self_attn.v_proj.bias', 'model.layers.28.mlp.down_proj.bias', 'model.layers.28.mlp.gate_proj.bias', 'model.layers.28.mlp.up_proj.bias', 'model.layers.28.self_attn.k_proj.bias', 'model.layers.28.self_attn.o_proj.bias', 'model.layers.28.self_attn.q_proj.bias', 'model.layers.28.self_attn.v_proj.bias', 'model.layers.29.mlp.down_proj.bias', 'model.layers.29.mlp.gate_proj.bias', 'model.layers.29.mlp.up_proj.bias', 'model.layers.29.self_attn.k_proj.bias', 'model.layers.29.self_attn.o_proj.bias', 'model.layers.29.self_attn.q_proj.bias', 'model.layers.29.self_attn.v_proj.bias', 'model.layers.3.mlp.down_proj.bias', 'model.layers.3.mlp.gate_proj.bias', 'model.layers.3.mlp.up_proj.bias', 'model.layers.3.self_attn.k_proj.bias', 'model.layers.3.self_attn.o_proj.bias', 'model.layers.3.self_attn.q_proj.bias', 'model.layers.3.self_attn.v_proj.bias', 'model.layers.30.mlp.down_proj.bias', 'model.layers.30.mlp.gate_proj.bias', 'model.layers.30.mlp.up_proj.bias', 'model.layers.30.self_attn.k_proj.bias', 'model.layers.30.self_attn.o_proj.bias', 'model.layers.30.self_attn.q_proj.bias', 'model.layers.30.self_attn.v_proj.bias', 'model.layers.31.mlp.down_proj.bias', 'model.layers.31.mlp.gate_proj.bias', 'model.layers.31.mlp.up_proj.bias', 'model.layers.31.self_attn.k_proj.bias', 'model.layers.31.self_attn.o_proj.bias', 'model.layers.31.self_attn.q_proj.bias', 'model.layers.31.self_attn.v_proj.bias', 'model.layers.4.mlp.down_proj.bias', 'model.layers.4.mlp.gate_proj.bias', 'model.layers.4.mlp.up_proj.bias', 'model.layers.4.self_attn.k_proj.bias', 'model.layers.4.self_attn.o_proj.bias', 'model.layers.4.self_attn.q_proj.bias', 'model.layers.4.self_attn.v_proj.bias', 'model.layers.5.mlp.down_proj.bias', 'model.layers.5.mlp.gate_proj.bias', 'model.layers.5.mlp.up_proj.bias', 'model.layers.5.self_attn.k_proj.bias', 'model.layers.5.self_attn.o_proj.bias', 'model.layers.5.self_attn.q_proj.bias', 'model.layers.5.self_attn.v_proj.bias', 'model.layers.6.mlp.down_proj.bias', 'model.layers.6.mlp.gate_proj.bias', 'model.layers.6.mlp.up_proj.bias', 'model.layers.6.self_attn.k_proj.bias', 'model.layers.6.self_attn.o_proj.bias', 'model.layers.6.self_attn.q_proj.bias', 'model.layers.6.self_attn.v_proj.bias', 'model.layers.7.mlp.down_proj.bias', 'model.layers.7.mlp.gate_proj.bias', 'model.layers.7.mlp.up_proj.bias', 'model.layers.7.self_attn.k_proj.bias', 'model.layers.7.self_attn.o_proj.bias', 'model.layers.7.self_attn.q_proj.bias', 'model.layers.7.self_attn.v_proj.bias', 'model.layers.8.mlp.down_proj.bias', 'model.layers.8.mlp.gate_proj.bias', 'model.layers.8.mlp.up_proj.bias', 'model.layers.8.self_attn.k_proj.bias', 'model.layers.8.self_attn.o_proj.bias', 'model.layers.8.self_attn.q_proj.bias', 'model.layers.8.self_attn.v_proj.bias', 'model.layers.9.mlp.down_proj.bias', 'model.layers.9.mlp.gate_proj.bias', 'model.layers.9.mlp.up_proj.bias', 'model.layers.9.self_attn.k_proj.bias', 'model.layers.9.self_attn.o_proj.bias', 'model.layers.9.self_attn.q_proj.bias', 'model.layers.9.self_attn.v_proj.bias']
- This IS expected if you are initializing LlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
INFO  Format: Converting `checkpoint_format` from `gptq` to internal `gptq_v2`.                                                                                                                                 
INFO  Format: Converting GPTQ v1 to v2                                                                                                                                                                          
INFO  Format: Conversion complete: 0.08502769470214844s                                                                                                                                                         
✅ Text encoder loaded! (VRAM: 5635.26 MB)

[2] Preparing Transformer from: azaneko/HiDream-I1-Fast-nf4
     Type: NF4
     Loading Transformer... (May download files)
FETCH ComfyRegistry Data: 70/82
FETCH ComfyRegistry Data: 75/82
FETCH ComfyRegistry Data: 80/82
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
     Moving Transformer to CUDA...
✅ Transformer loaded! (VRAM: 14884.69 MB)

[3] Preparing Scheduler: FlashFlowMatchEulerDiscreteScheduler
     Using Scheduler: FlashFlowMatchEulerDiscreteScheduler

[4] Loading Pipeline from: azaneko/HiDream-I1-Fast-nf4
     Passing pre-loaded components...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 13.06it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 10.72it/s]
     Pipeline structure loaded.

[5] Finalizing Pipeline...
     Assigning transformer...
     Moving pipeline object to CUDA (final check)...
     Warning: Could not move pipeline object to CUDA: HIP out of memory. Tried to allocate 80.00 MiB. GPU 0 has a total capacity of 23.98 GiB of which 34.00 MiB is free. Of the allocated memory 23.35 GiB is allocated by PyTorch, and 376.59 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables).
     Attempting CPU offload for NF4...
     ✅ CPU offload enabled.
✅ Pipeline ready! (VRAM: 12881.07 MB)
Model fast-nf4 loaded & cached!
--- Loading Model Type: fast-nf4 ---
Model Path: azaneko/HiDream-I1-Fast-nf4
NF4: True, Requires BNB: False, Requires GPTQ deps: True
Using alternate LLM: False
(Start VRAM: 12881.07 MB)
Cache check for key: fast-nf4_standard
Cache contains: ['fast-nf4_standard']
Using cached model for fast-nf4_standard
Using model's default scheduler: FlashFlowMatchEulerDiscreteScheduler
Creating Generator on: cuda:0

--- Starting Generation ---
Model: fast-nf4, Res: 1024x1024, Steps: 16, CFG: 0.0, Seed: 0
Using standard sequence lengths: CLIP-L: 77, OpenCLIP: 150, T5: 256, Llama: 256
Skipping pipe.to(cuda:0) (CPU offload enabled).
Executing pipeline inference...
Memory access fault by GPU node-1 (Agent handle: 0x56125fe897a0) on address 0x7f3c94a05000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)

**Comment by basicist** [comment]
SOLVED (For myself)

Error:
Memory access fault by GPU node-1 (Agent handle: 0x56125fe897a0) on address 0x7f3c94a05000. Reason: Page not present or supervisor privilege.

I resolved the issue by running the following command within my python virtual environment (venv):

python main.py --reserve-vram 2

OS: ArchLinux
GPU: AMD 7800 XT
Python venv: 3.11.14

ROCm/Torch Installation:
Followed the installation guide from the [ComfyUI GitHub](https://github.com/Comfy-Org/ComfyUI)

After installing the required dependencies from requirements.txt, I ran the following to install the correct versions of PyTorch for ROCm for my GPU:

pip uninstall -y torch torchvision torchaudio
pip install --pre torch torchvision torchaudio --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/

Root Cause:
It seems the issue was related to my OS not having access to safely allocated VRAM. Using the --reserve-vram 2 flag resolved the problem by reserving VRAM manually.
